# Checks for style guide conformity on pull requests that change js files
name: ESLint
on:
  pull_request:
    paths: ["**.js"]

jobs:
  eslint-check:
    name: Code style check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Lint
      uses: krizzu/eslint-check-action@v1.1.0
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        eslintFiles: "src/js"
        eslintConfig: ".eslintrc.json"
